version: '2'
services:

  kafka:
    build: kafka/
    container_name: kafka
    environment:
      - "KAFKA_FQDN=kafka"
    volumes:
      - /etc/localtime:/etc/localtime
      - kafka:/data/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
      - "9999:9999"

  bmp_collector:
    image: openbmp/collector
    container_name: bmp_collector
    environment:
      - "KAFKA_FQDN=kafka"
    volumes:
      - /etc/localtime:/etc/localtime
      - bmp_collector:/config
    ports:
      - "5000:5000"
    depends_on:
      - kafka

  bmp_db:
    image: openbmp/mysql
    container_name: bmp_db
    environment:
      - "KAFKA_FQDN=kafka"
      - "MYSQL_ROOT_PASSWORD=openbmp"
      - "MEM=4"
      - "REINIT_DB=1"
    volumes:
      - mysql_1:/data/mysql 
      - /etc/localtime:/etc/localtime
    ports:
      - "3306:3306"
      - "8001:8001"
    expose:
      - "3306"
      - "8001"
    depends_on:
      - kafka

  network-rib:
    build: network-rib/
    container_name: network-rib
    environment:
      - "NETWORK_RIB_REST_API_PORT=4000"
      - "NETWORK_RIB_REST_API_USER=juniper"
      - "NETWORK_RIB_REST_API_PASSWORD=juniper"
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "4000:4000"
    expose:
      - "4000"

  netflow-correlator_1:
    build: netflow-correlator/
    container_name: netflow-correlator_1
    environment:
      - "KAFKA_ADDR=kafka"
      - "KAFKA_PORT=9092"
      - "KAFKA_CONSUMER_TOPIC=netflow_1"
      - "OPENBMP_REST_ADDR=bmp_db_1"
      - "OPENBMP_REST_PORT=8001"
      - "OPENBMP_REST_USER=openbmp"
      - "OPENBMP_REST_PASSWORD=CiscoRA"
      - "STATSD_METRICS=true"
      - "STATSD_HOST=213.99.17.76"
      - "STATSD_PORT=8125"
    volumes:
      - /etc/localtime:/etc/localtime
    depends_on:
      - kafka
      - bmp_db_1

#  netflow-correlator_2:
#    build: netflow-correlator/
#    container_name: netflow-correlator_2
#    environment:
#      - "KAFKA_ADDR=kafka"
#      - "KAFKA_PORT=9092"
#      - "KAFKA_CONSUMER_TOPIC=netflow_2"
#      - "OPENBMP_REST_ADDR=bmp_db_2"
#      - "OPENBMP_REST_PORT=8001"
#      - "OPENBMP_REST_USER=openbmp"
#      - "OPENBMP_REST_PASSWORD=CiscoRA"
#      - "STATSD_METRICS=true"
#      - "STATSD_HOST=213.99.17.76"
#      - "STATSD_PORT=8125"
#    volumes:
#      - /etc/localtime:/etc/localtime
#    depends_on:
#      - kafka
#      - bmp_db_2

  netflow-collector_1:
    build: netflow-collector/
    container_name: netflow-collector_1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
     - "SERVICES_CLIENT=9995"
     - "KAFKA_ADDR=kafka"
     - "KAFKA_PORT=9092"
     - "KAFKA_PRODUCER_TOPIC=netflow_1"
     - "NETFLOW_PORT=9995"
    expose:
      - "9995/udp"
    depends_on:
      - kafka

#  netflow-collector_2:
#    build: netflow-collector/
#    container_name: netflow-collector_2
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#    environment:
#     - "SERVICES_CLIENT=9995"
#     - "KAFKA_ADDR=kafka"
#     - "KAFKA_PORT=9092"
#     - "KAFKA_PRODUCER_TOPIC=netflow_2"
#     - "NETFLOW_PORT=9995"
#    expose:
#      - "9995/udp"
#    depends_on:
#      - kafka

  lb:
    build: lb/
    container_name: lb
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
     - "SERVICES_LB=9995"
    ports:
     - "9995:9995/udp"

#  netflow-collector_dummy:
#    build: netflow-collector/
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#    environment:
#     - "SERVICES_CLIENT=9995"
#     - "KAFKA_ADDR=xxxxx"
#     - "KAFKA_PORT=9092"
#     - "KAFKA_PRODUCER_TOPIC=xxxxx"
#     - "NETFLOW_PORT=8888"
#    expose:
#      - "9995/udp"
#    depends_on:
#      - kafka


#######################
# Named container     #
#######################
 
volumes:
  # Named volume
  mysql_1:
  mysql_2:
  kafka:
  bmp_collector:

